if filereadable( expand( '$HOME/.vim/.vimrc.options' ) )
  source $HOME/.vim/.vimrc.options
endif


if filereadable( expand( '$HOME/.vim/.vimrc.keybind' ) )
  source $HOME/.vim/.vimrc.keybind
endif

if filereadable( expand( '$HOME/.vim/.vimrc.plugins' ) )
  source $HOME/.vim/.vimrc.plugins
endif

set nocompatible
filetype off

filetype plugin indent on
filetype indent on

" 256色使う設定
set t_Co=256

syntax on

highlight Normal ctermbg=none

