#!/bin/bash

INSTANCE_NAME=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].Tags[?Key == `Name`].Value[][]' | jq -r '.[]' | fzf)
INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$INSTANCE_NAME" --query 'Reservations[*].Instances[*].InstanceId[]' | jq -r '.[]')

aws ssm start-session --target $INSTANCE_ID

